---
meta:
  interpolate-vars: &interpolate-vars
    task: interpolate-vars
    image: ronnie-build-image
    params:
      VARS: vars-file/ci/secret/pipeline/hello-world.yml
    input_mapping:
      files: repo-with-secrets
      vars-file: repo-with-secrets
    output_mapping:
      interpolated-files: repo-with-secrets-and-vars

resource_types:
- name: concourse-pipeline
  type: registry-image
  source:
    repository: concourse/concourse-pipeline-resource
    tag: "6.0.1"

resources:
- name: repo
  type: git
  source:
    uri: https://github.com/FezekaH/ronnie-api-platform.git

- name: hello-world-pipeline-trigger
  icon: bike
  type: semver
  source:
    branch: pipeline-trigger
    driver: git
    file: hello-world-trigger-file
    uri: https://github.com/FezekaH/ronnie-api-platform.git
    private_key: ((github_deployment_key.private_key))

jobs:
- name: hello-world-job
  plan:
  - get: repo
    trigger: true  # tell Concourse to trigger this job when new versions are emitted
  - task: hello-world-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      outputs:
      - name: the-artifact
      run:
        # This is a neat way of embedding a script into a task
        path: sh
        args:
        - -cx
        - |
          ls -l .
          echo "hello from another step!" > the-artifact/message
  # Add a second task that reads the contents of the-artifact/message
  - task: read-the-artifact
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      # To receive "the-artifact", specify it as an input
      inputs:
      - name: the-artifact
      run:
        path: sh
        args:
        - -cx
        - |
          ls -l .
          cat the-artifact/message
  - put: hello-world-pipeline-trigger
    params:
      bump: minor